# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20171202_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20)),
                ('ts', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AskMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_id', models.CharField(max_length=20)),
                ('ts', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='chanel_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='chanel_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='askmessage',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_messages', to='bot.Team'),
        ),
        migrations.AddField(
            model_name='answermessage',
            name='ask_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_messages', to='bot.AskMessage'),
        ),
    ]
