# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20171202_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel_id', models.CharField(max_length=100, null=True)),
                ('chanel_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='chanel_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='chanel_name',
        ),
        migrations.AddField(
            model_name='channels',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='bot.Team'),
        ),
    ]
