# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20171202_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='active_chanel',
            field=models.BooleanField(default=False),
        ),
    ]
