# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_channels_active_chanel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AskMessage',
            new_name='LeaveMessage',
        ),
    ]
